### ISSUE TITLE
Starting point of indent for @html-eslint/indent with HTML Javascript template literals

### ISSUE THREAD

**Issue by jpradelle** [yeonjuan/html-eslint#241] opened 2024-12-03 10:08 UTC
When using javascript HTML literals, it always requests to start at 0 for top level tag, do you think it could be updated to handle cases like this:
```js
import {html, LitElement} from 'lit';

export class TestTest extends LitElement {
  render() {
    return html`
      <p>Expected indent to start like that, at 6</p>
    `;
  }
}
customElements.define('test-test', TestTest);
```
Current output is
```
test-test.js
  8:1  error  Expected indentation of 0 space but found 6 space  @html-eslint/indent
```

I also see a bit more complex cases like that:
```js
import {html, LitElement} from 'lit';
import {repeat} from 'lit/directives/repeat.js';

export class TestTest extends LitElement {
  render() {
    return html`
      <p>Expected indent to start like that, at 6</p>
      ${repeat([], item => html`
        <p>Expected indent to start like that, at 8</p>
      `)}
      ${repeat(
          [],
          item => html`
            <p>Expected indent to start like that, at 12</p>
          `)}
      ${
        repeat(
            [],
            item => html`
              <p>Expected indent to start like that, at 12</p>
            `)
      }
    `;
  }
}
customElements.define('test-test', TestTest);
```

I think we would like initial indent reference to be something like start position of 1st non indent char of line containing html` + 1 indent level.

**Comment by yeonjuan** [comment] 2024-12-03 13:14
Hi @jpradelle Thanks for the reporting this issue.
> I think we would like initial indent reference to be something like start position of 1st non indent char of line containing html

This seems reasonable. let me fix it!

**Comment by yeonjuan** [comment] 2024-12-03 16:12
Hi @jpradelle, It's fixed in `v0.30.0` 👍

**Comment by yeonjuan** [comment] 2024-12-10 15:46
@jpradelle Starting with v0.31.0, you can adjust the indent depth of an Attribute separately.
https://html-eslint.org/docs/rules/indent#customizing-options
```
  "@html-eslint/indent": ["error", 2, {"Attribute": 2}]
```

**Comment by jpradelle** [comment] 2024-12-11 10:22
Hi thanks a lot, works exactly as expected for attributes.

About previous comment on template literal root base indent, sorry to bother you again do you think it could be updated or an option could be added:

On this example:
```js
import {LitElement, html} from 'lit';
import {when} from 'lit/directives/when.js';

export class TestTest extends LitElement {
  render() {
    return html`
      ${when(true, () => html`
        <foo-bar
            .baz="${value => html`
              <foo-baz
                  bar></foo-baz>
            `}"></foo-bar>
      `)}
    `;
  }
}
customElements.define('test-test', TestTest);
```
Report is 
```
test-test.js
   8:1  error  Expected indentation of 10 space but found 8 space   @html-eslint/indent
   9:1  error  Expected indentation of 14 space but found 12 space  @html-eslint/indent
  10:1  error  Expected indentation of 22 space but found 14 space  @html-eslint/indent
  11:1  error  Expected indentation of 26 space but found 18 space  @html-eslint/indent
```

Which means fixed version is 
```js
import {LitElement, html} from 'lit';
import {when} from 'lit/directives/when.js';

export class TestTest extends LitElement {
  render() {
    return html`
      ${when(true, () => html`
          <foo-bar
              .baz="${value => html`
                        <foo-baz
                            bar></foo-baz>
              `}"></foo-bar>
      `)}
    `;
  }
}
customElements.define('test-test', TestTest);
```

Indent base reference seems to be the opening curly brace
```
              .baz="${value => html`
                      ^
                      |
```

Could it be base indent of line on which template opening is
```
              .baz="${value => html`
              ^
              |
```

I think both can make sense, but currently in some complex cases, indent can increase a lot very fast

**Comment by yeonjuan** [comment] 2024-12-11 16:26
@jpradelle In the current version, when tempalte literals are nested, the indents keep stacking up. This seems to be the cause, and I've raised a PR to fix it. https://github.com/yeonjuan/html-eslint/pull/247
It has also been prereleased. (0.31.1-alpha.0)
I'd appreciate it if you could check it out with the pre-release version.
```
// don't need to upgrade parser version. only eslint-plugin published
npm install -D html-eslint/eslint-plugin@0.31.1-alpha.0
```

**Comment by jpradelle** [comment] 2024-12-11 17:29
Awesome, works exactly as expected: applying this on my project reported no false positive, and it reported few issues as expected :)
Thank you so much !

**Closed** 2024-12-12 10:43 UTC
